minjoo/boj11399.java, minjoo/programmers_level2_tuple.java
=> 220103 quiz

minjoo/boj1074.java, minjoo/programmers_level2_lightRoadCycle.java
대표적인 이분탐색 문제로, 그리디 문제에 속하는 문제이다. 어떻게 Z를 이동할지 식을 세우는 게 관건으로, 가장 먼저 시작하는 4개의 정사각형 칸의 값은 (rx2)+c로 정의된다.
이후로 **재귀를 이용해 이전 값들을 더해서 이동하는 식**으로 진행되며, 해당 식은 정사각형의 size에 따라 진행된다.
시간 복잡도는 size를 N이라 했을 때, 최악의 경우 O(2^N)이 된다. N<=15이므로, 1024x32 = 약 4천이 되므로 0.5초 내로 해결이 가능하다.
---
BFS나 DFS같이 자료구조, 재귀를 이용한 탐색이 아닌 순수하게 완전 탐색과 백트래킹을 사용해 푸는 문제. **visited 배열을 어떻게 만드는지**가 중요했던 문제이다. 테스트 케이스를 살펴보면, 무조건 시작점에 도착했다 해서 종료하는 것이 아닌, 어떤 특정 지점에 도착했으나 **4방향의 길을 모두 이용해 더 이상 앞으로 나아갈 수 없을 때** 사이클을 종료하게 된다.
시간 복잡도는 grid 문자열이 그리는 배열의 행의 길이 N, 열의 길이를 M이라 했을 때, O(NxM)을 모두 탐색하고 조건을 충족했을 때, 가지치기로 빠져나오는 것이므로 최악일 경우 O(NM)인데, N<=500, M<=500의 조건을 성립하므로 500x500 = 250000이므로 1초 이내로 연산이 가능하다.
추가로 사이클의 길이를 오름차순으로 정렬하라는 조건이 있어 Arrays.sort()를 사용했다.
=> 210115 quiz

soyeon/BackJoon_1074_Z.java, soyeon/BackJoon_1074_Z_TimeOut.java, soyeon/Programmers_42587_printer.java, soyeon/backJoon_15649_NAndM1.java
**<시간복잡도>**
대기목록 최대 사이즈가 100까지로, 범위가 굉장히 좁은편.
따라서 최악의 경우, 맨 앞거 하나와 그 뒤의 99개를 전부 비교하면 100*99 =9900 이다.
때문에 O(N^2) 의 시간복잡도로도 충분히 통과할 수 있다.
**<풀이방법>**
굳이 Queue를 쓰지않고 ArrayList로도 충분히 풀 수 있었다.
맨 처음 location 위치의 문서가 어떤건지 기억하기 위해
`readInput()`으로 `ArrayList<Print> print`에 문서 이름(char id)을 매핑시켜주었는데,
앞에서부터 차례대로 A B C D ... 로 매겨주었다.
----------------
**<시간복잡도>**
전형적인 순열문제로, O(N!) 의 시간복잡도를 가진다.
`N`의 범위가 8까지이므로 충분하다.
**<풀이방법>**
순열로 길이가 `M`인 배열을 채우고 바로 StringBuilder에 저장한다.
`N`과 `M`이 헷갈려서 뒤바꿔적는 실수를 저질렀다.
앞으로는 간단하더라도 변수명을 의미있게 지어줘야겠다ㅠ
=> 2022-01-05 수

soyeon/BackJoon_9663_NQueen_FAIL.java, soyeon/Programmers_42577_PhoneNumberList.java
**<풀이과정>**
1. `int[] phone_book`의 길이가 1 ~ 100만이므로 이중반복문으로 비교하는 것은 불가능하다.
2. 예시를 보고 각 전화번호의 3글자까지가 접두사라고 생각함 => FAIL
3. `substring(0,3)` 한 다음 `set`에 넣고 만약 중복되면 `return false` 하는 로직으로 구현 => 3글자까지만 땀 (틀림) + 시간초과
4. 이쯤부터 뭔가 잘못됨을 느끼고 문제를 다시봄 => 접두사는 각 문자 3글자까지가 아니란 것을 깨달음..
5. 문자열 숫자 정렬은 숫자의 크기로 정렬되는 것이 아니라 **사전순** 정렬됨
ex)
{13, 121, 1256} => {13, 121, 1256}
{"13", "121", "1256"} => {"121", "1256", "13"}
6. `phone_book` 정렬 후 `i`번째와 `i+1`번째만 비교
**<시간복잡도>**
O(NlogN + N)
---------------------
**<풀이과정>**
1. `isPossible(y, x)`로 `(y, x)`가 현재 놓인 퀸들과 가로, 세로, 대각선에 놓이게 될 경우 가지치기
2. 이중반복문을 돌 때 `y=0`, `x=0` 으로 둔 것과 `y=cy`, `x=0`로 둔 것의 차이는 중복이 되냐 안되냐 차이
=> 답이 달라지는 것도 중복으로 카운트돼서?
=> 그러면 `y=cy`, `x=cx`로 둔 것과 `y=cy`, `x=0`의 차이는 무엇인지.. ㅠ 더 중복을 줄인것 같은데 왜 답이 달라지는지!
3. 어쨌거나 테케는 맞게 나오지만.. 멤초가 뜹니다. …
=> 2022-01-07 금

soyeon/BackJoon_15681_TreeAndQuery.java, soyeon/Programmers_42746_biggestNumber.java, soyeon/Programmers_86052_LightPathCycle.java
1. 각 정점을 방문했을 때의 방향에 따라, 다른 경로로 나아갈 수 있으므로 visited[y][x][d] 3차원 배열 선언
2. 문제에서의 '사이클'이라는 개념이 애매해서 처음 풀 때 애먹음
-----------------------
**<시간복잡도>**
1. 특정 노드가 루트노드이므로 탐색할 때 루트노드부터 시작하지 않으면 서브쿼리에 딸린 노드가 몇개인지 파악이 불가능하다.
2. 따라서 매 탐색마다 찾으려는 노드를 만난 시점부터 카운트하는 방식을 떠올렸지만, query의 수가 10만, 노드의 개수도 10만까지라 불가능
3. 다른 접근방법이 필요했지만 막상 잘 떠오르지 않아 일단 위 방법으로 제출하니 역시나 시간초과 ㅎㅎ;;
4. 일단 사람은 맞아봐야 안다고 시초가 뜨고나니 애초에 각 노드를 한번만 탐색하면서 아래에 딸린 자식 노드들이 몇개인지 저장하면 되지 않을까..!? 그 후 저장해놓은 `visited` 배열에서 query만 출력하면 됨
5. 고로 시간 복잡도는 O(N)
----------------------
**<시간복잡도>**
1. `numbers`의 길이가 10만까지이므로 순열로 접근하는 것은 불가능
2. 단어를 사전순으로 내림차순해 이어붙이면 가장 큰 수가 나온다
3. 앞자리가 0이 나오는 경우엔 앞자리 0을 제거하고 리턴
4. O(NlogN)
=> Programmers_86052_LightPathCycle 미해결 문제 완료

minjoo/boj15681.java, minjoo/programmers_level2_theBiggestNumber.java
트리에서의 DP 알고리즘을 시작하는 전형적인 문제. 쿼리의 개수 Q만큼 N-1개의 트리 루트를 탐색하면, 최악의 경우 10만x10만이 돼서 100억이 돼 무조건 시간초과가 나게 됩니다. 따라서 메모이제이션으로 탐색을 한 번만 진행해 모두 기록한 다음, 쿼리마다 각 시작점에 저장된 값을 불러와 출력하는 게 제일 베스트 알고리즘인 문제.
---
Arrays.sort를 이용해, 각 숫자의 가장 큰 자리수(10의 자리, 1의 자리 등) 하나만 비교해 큰 수대로 재정렬하고 그걸 문자열에 이어 붙여줬습니다.
number의 길이가 10만 이하여서 문자열로 답을 리턴해야 했고, numbers의 원소 개수가 최대 1천개였기에 만약 dfs로 순열 세우듯 풀었다면 시간 초과로 불가능했을 것입니다. (제 코드 최악으로 걸린 시간이 3초)
=> 220110 quiz

soyeon/BackJoon_10026_RedGreenColorWeakness.java, soyeon/Programmers_42839_FindPrimeNumber.java
중복조합으로 무작위 수를 만든다음, Set에 넣어 `isPn()`으로 소수인지 아닌지 판별
에르테네스의 체로 풀면 훨씬 빠른 시간안에 풀 수 있다.
--------------
dfs 완탐
=> 2022-01-11 화

minjoo/boj10026.java, minjoo/boj2206.java, minjoo/programmers_level2_findPrimeNumber.java, minjoo/programmers_level2_theShortestDistanceGameMap.java
로봇 청소기랑 비슷한 DFS 탐색 문제
---
BFS 탐색과 백트래킹이 합쳐진 문제. 메모리 초과가 제일 해결하기 어려운 문제로, 왜 이런 문제가 골드 4인가 했더니 백트래킹을 정확하게 해야 192MB 내로 완료가 가능하다.
N과 M은 각각 1천 이하의 자연수로, map과 visited를 모두 선언해야 하는데 공간 복잡도의 경우 최악에는 N*M*4 = 400만byte = 400MB로 초과가 날 수 밖에 없다. 근데 왜 되는거지 잘 모르겠네요.... 심지어 제 거 메모리 초과가 나는데 다른 사람거랑 차이가 뭔지 모르겠어서...
??
---
전형적인 소수 찾기 문제로 에라토스테네스의 체와 해시맵을 통한 중복 수 거르기, dfs로 순열 세우기를 하면 된다.
---
=> 220112 quiz

minjoo/boj2629.java, minjoo/programmers_level2_joystick.java
Knapsack 문제로 가방에 들어갈 수 있는 최대 무게의 최대 가치를 구하는 것이 아닌, 다른 추를 넣었을 때, 탐색이 가능한 무게인지 확인하는 문제입니다.
---
정말 그리디다운 문제로 모든 경우의 수를 탐색하는 방법으로 진행됩니다.
처음에 풀 때는 각 알파벳과 A의 차이값 중, (알파벳)-'A' or 'A'-(알파벳)을 비교해 최소값을 더하는 형태로 진행했으나, 문제를 자세히 살펴보니 앞뒤로 자유롭게 이동할 수 있다는 뜻은 맨 처음에 시작할 때도 맨 앞에서 맨 뒤로 이동이 가능하다는 말이었습니다.
이 경우를 고려해 푸니 풀리더라구요.... 처음엔 틀린 값이 계속 나오길래 왜 그런가 싶었습니다.
=> 220113 quiz

soyeon/BackJoon_2662_CorporateInvestment.java, soyeon/Programmers_12985_ExpectedDraw.java
**<시간복잡도>**
1. 처음에 큐로 돌릴 생각을 했는데, N의 최대 크기가 100만이라 이걸 큐에 넣고 두개씩 인접하는 것끼리 사라지게 하며 큐가 빌때까지 돌리면 터질거라고 생각해서 포기
2. 그리디라고 생각하고 접근
3. 앞에서부터 차례대로 인접한 두개가 경기를 해 이긴승자만 하나가 되므로
1 2 / 3 4 / 5 6 / 7 8
1  /   2  /   3  /  4      --- 1
1      /      2           --- 2
1                   --- 3
이런 식으로 숫자들이 생성된다.
여기서 만약 A=4, B=7 이라면 3번의 대진 후에 만나게된다.
결국 4가 2가 되고, 2에서 1이 된다.
7 또한 7에서 4가 되고 ,4에서 2가되고 마지막에 1이 된다.
즉, A와B를 2로 나눠가며 서로 같은 수가 됐을때 멈추면 된다.
A와B가 짝수일땐 그대로 나누면 되지만 홀수일때 2로 나눴을때는 0.xxx , 1.xxx 이런식으로 나오게 되는데
0.xxx -> 1
1.xxx -> 2
가 된다. 때문에 Math.ceil(A/2) 를 해주어야 한다.
4. 그러므로 O(N/2)
5. (double)(a/2) vs (double)a/2 의 차이를 명확히 알았어야 한다.
--------------
**<시간복잡도>**
1. 각 기업의 투자금액을 0~amount만원까지 했을 경우로 생각한다.
2. O(N+1)
3. 근데 틀렸다. 왜죠..ㅠ
4. 풀어놓고 정답률 38%치고 너무 쉽게 풀렸다곤 생각했는데 역시나ㅠ
=> 2022-01-14 금

minjoo/programmers_level2_expectedDraw.java
2^20번 대진을 한다는 문제 조건을 보고 이분탐색이구나! 를 바로 깨닫고 시도했습니다.
중요한 건 주어지는 a랑 b가 순서대로가 아닌, a가 더 클 수도 있고 b가 더 클 수도 있다는 점입니다. left와 right의 조건은 left가 작은 것, right가 큰 수이므로 둘을 먼저 배치해주는 로직 후에 이분탐색을 진행하면 깔끔하게 마무리 됩니다.
다른 사람의 답안도 봤는데 `return Integer.toBinaryString((a-1)^(b-1)).length();` 한 줄로 끝나는 거 보고 어리둥절 했습니다....
---
=> 220114 quiz

moontek/baekjoon/중량제한.java
=> 0118 Baekjoon Update

minjoo/boj1939.java, minjoo/programmers_level2_searchRanking.java
kruskal-mst 문제로, **다리로 연결된 부분을 하나의 그룹으로 연결하고 prorityQueue로 cost가 최대값**이 되는 걸 출력하는 문제.
N이 1만, M이 10만으로 만약 배열을 세워 단순 탐색을 한다면 O(MxN^2)=최악 1억x10만의 연산으로 시간 초과가 날 수 밖에 없다. 따라서 pq를 사용해 정렬 및 탐색, 크루스칼로 연결된 곳만 탐색함으로써 O(MxlogN)으로 시간 복잡도를 줄일 수 있다.
---
답을 좀 시간 들여 살펴봐야 하는데 못 살펴봤다.... 해쉬의 중복값 제거를 이용하는 문제로 일반 그리디로 풀면 멸망한다.
=> 220117 quiz

soyeon/Programmers_42585_TruckCrossingTheBridge.java
=> 2022-01-20 목

minjoo/boj1655.java, minjoo/programmers_level2_passingBridgeTruck.java
**큐나 링크드리스트와 같은 FIFO 자료구조**를 이용하는 문제. 둘 중 어느 걸 사용하더라도 상관 없다.
대신에 트럭 무게 배열을 순서대로 자료구조에 넣어보되, 해당 무게가 다리의 한계 무게인지, 트럭의 개수가 다리의 길이보다 짧거나 같은지를 비교하며 진행해야 한다. 때문에 for(각 트럭) 내에서 bfs 형식으로 쭉 돌며 비교해주는 게 키 포인트.
---
힙 탐색을 이용한 문제로, N이 10만 이하로 만약 단순 탐색을 진행하면 O(NlogN)=약 1억 이상이라는 연산 횟수가 나올 수 있으므로 0.2초 내로 연산이 완료돼야 하는 조건 상 단순 탐색은 불가능하다.
따라서 최소 힙/최대 힙을 만들어, 각 힙 값을 비교해 절반씩 요소를 넣어줘야 한다.  이 때, **작은 값을 출력해야 하기 때문에 최대힙의 특성상 가장 작은 값을 먼저 꺼낼 수 있으므로 비교 끝 부분에 min의 최대값이 max의 최소값보다 작다면 max 힙으로 옮겨주는 것이다.**
=> 220120 quiz

minjoo/boj2933.java, minjoo/programmers_level2_candidateKey.java
Hash~의 중복 제거와 검색 알고리즘+dfs로 조합 부분 집합을 만드는 알고리즘
---
=> 220126 quiz

minjoo/boj2749.java, minjoo/programmers_level2_rotatingBracket.java
피사노 주기를 이용한 문제로, modular가 1백만이기 때문에 이용이 가능하다. 다음 문제인 피보나치 수 6에서는 사용 불가능한 것으로 보임....
N의 최대 값이 10의 18승, 즉 100경으로 기존 피보나치 수열처럼 dp로 하면 메모리 특성상 터지는 게 문제... 이 때, 피사노 주기는 피보나치 수가 특정한 주기(15x10^(k-1))를 지났을 때 다시 똑같은 숫자가 나온다는 점을 이용한 수학 정리이다. 모듈러의 공식은 10^(k).
따라서 시간복잡도는 O(N%(15x10^(k-1))로, 최악의 연산의 경우... 계산이 안 되지만 아무튼 2초 내로 가능한 듯 보인다.
이외에도 행렬로 푸는 문제가 있는데 아래 링크를 참고하길 바람.
참고: https://www.acmicpc.net/blog/view/28
---
프로그래머스는 괄호 문제를 참 좋아하는 것 같다. 스택과 그리디(단순 구현)로 풀면 되는 문제.
회전하는 것은 S의 맨 앞 글자를 맨 뒤로 매 차례마다 보내주면 된다.
시간 복잡도는 O(N^2) = 최악의 경우 1백만. 0.01초 내로 연산이 가능하다.
=> 220129 quiz

minjoo/boj10830.java, minjoo/programmers_level2_delivery.java
오랜만에 플로이드 와샬을 이용해 이동이 가능한지 여부를 따지는 문제.
NxN 맵을 탐색하며, 자신을 제외한 경유지를 들러 K 이하의 거리가 나오는지 판단하는 알고리즘으로, 
경유지, 출발지, 도착지를 각 N회 만큼 탐색하기 때문에 시간 복잡도가 O(NxNxN) = 최악의 경우 125000번의 연산횟수가 나온다.
따라서 아무리 연산이 많아져도 1초 내로 가능하므로 괜찮다.
---
행렬 제곱을 구현한 후, 분할 정복을 이용해 제곱을 하면 된다. 이 때, pow 라는 Math의 함수를 이용하면 N회 연산이 log2B로 줄어드므로 1천억의 숫자가 40 정도의 작은 숫자가 되어버린다. 따라서 분할 정복을 이용하지 않는다면 시간 초과가 무조건 날 수 밖에 없다.
=> 220204 quiz

soyeon/BackJoon_10830_MatrixSquared.java, soyeon/Programmers_12978_Delivery.java
----------------
**<시간복잡도>**
1. 분할정복이지만 O(N^3)의 시간복잡도를 가짐
2. 짝수일 경우 N^4 = N^2 * N^2
3. 홀수일 경우 N^5 = N^4 * N
**<주의할 점>**
1. `B`도 `long`형으로 선언해야 한다. 범위가 `int`를 넘어서므로
2. 출력할 때에도 `%1000`을 해줘야 한다. 안그럼 끝에가서 틀림
----------------
-------------
**<시간복잡도>**
1. O(NlogN)
**<주의할 점>**
1. BFS로 풀거면 그냥 `Queue` 말고 `PriorityQueue`를 써야 한다.
2. 왜냐하면 최소비용순으로 방문처리가 되는 게 아니고, 먼저 넣은 순대로 방문처리가 되기 때문에
=> 2022-02-04 금

minjoo/boj11066.java, minjoo/programmers_level2_fatique.java, minjoo/programmers_level2_uncorrectRectangle.java
=> 220209 quiz

minjoo/programmers_level2_makeBigNumber.java
=> 220211 quiz

moontek/baekjoon/행렬곱셈.java
행렬곱셈
dp문제..
결국 인접행렬을 어떻게 분가르는지가 핵심
0 1 2 3 이렇게있으면
01 // 23
0 //123  || 123 // 0 
사실상 정리해보면
0// 123 | | 01//23 || 012//3
이렇게 3가지고려 그렇다면 6개정도되면
0// 12345 || 01 //2345 || 012 //345 || 0123//45 || 01234// 5 
이렇게됨
기존의 12345 정보를 쪼개고쪼개서 dp에저장하면끝
=> add : baekjoon quiz 1 upload

minjoo/boj10942.java
팰린드롬 확인을 하는 함수를 짜되, 이전 결과는 메모이제이션 해두고 영역을 좁혀가며 해당 영역이 이미 팰린드롬을 만족한다면 1을 리턴하는 형식으로 진행한다.
---
=> 220225 quiz

moontek/programmers/교점에 별 만들기.java
별찍기 
문제에서 주어진 식을 이용해 일치 평행체크후에 해쉬셋어넣고 검증해주기
=> add programmers 1EA

minjoo/boj7579.java, minjoo/programmers_level2_divideElectronicNetworkByTwo.java
=> 220228 quiz

soyeon/backJoon_7576_App.java, soyeon/programmers_86971_SplitPowerGridInTwo.java
냅색문제
dp[i][j] = i번째 앱까지 사용했을 때 j 비용으로 얻을 수 있는 최대 메모리
`dp[i][j] = Math.max(dp[i-1][j], dp[i-1][j-cost]+memory)`
---------------------------
완탐
1. 제거할 와이어 선정
2. 복사해둔 와이어 배열에 해당 와이어 제거
3. `init()` 해당 복사 와이어배열대로 이중리스트 생성
4. 생성된 이중리스트를 탐색, `dfs`로 몇개의 노드가 있는지 리턴(`num`)
5. 전체(`n`)에서 `num`을 빼주면 나머지 그룹의 노드개수(`diff`)
6. `num`과 `diff`의 차가 가장 적은 값 `min` 리턴
=> 2022-02-28 월

moontek/baekjoon/앱.java, moontek/baekjoon/탐머신.JAVA, moontek/programmers/모음사전.JAVA
앱은 이전에..
타임머신 : 벨만포드를 몰라서..봤습니다..
모음사전 : 5 +25 +125+625+ 3125 = 3905  
5나누고 갯수를 더해주는데
단 
A / AA / AAA / AAAA / AAAAA 
이므로 +1를 해준다
=> ADD : quiz 2

soyeon/BackJoon_11657_Timemachine.java, soyeon/Programmers_76502_RotateBracket.java, soyeon/Programmers_84512_VowelDictionary.java
1. 음의 가중치가 있어 기존 BFS로 풀 수 없음 -> 벨만포드 알고리즘 사용
2. `N=500`  `M=6000`일 때 가중치가 -10000이라면 -300억의 값이 발생하게 되므로, `int[] costs`일 경우 **underflow**가 발생 -> `long[] costs` 선언해야 함
---------------
구현 문제, 그대로 구현
----------------
구현문제, 온전한 괄호를 판별하는 로직을 짜는 것이 중요
=> 2022-03-02 수

moontek/baekjoon/플로이드.JAVA, moontek/programmers/영어끝말잇기.JAVA
단순 플로이드
i ~j이면
i k k j 와 i~j를 비교하면끝
해쉬사용하여 중복검사 + 끝말잇기검사하기
=> ADD : 1 baekjoon 1 pg quiz

minjoo/boj11404.java, minjoo/programmers_level2_englishEndTalk.java
=> 220304 quiz

minjoo/boj2151.java, minjoo/programmers_level2_binaryChangeRepeat.java
BOJ 2151 거울 설치
프로그래머스 이진 변환 반복하기
=> 220307 quiz

minjoo/boj16954.java, minjoo/programmers_level2_cache.java
BOJ 11954 움직이는 미로 탈출
프로그래머스 캐시
=> 220310 quiz

moontek/baekjoon/움직이는미로탈출.java, moontek/programmers/캐시.java
움직이는 미로탈출 
전체줄이 내려오는건줄알앗는데 벽만 내려오는거임 그거 생각하고 bfs 돌리면 완료
캐시 
중복체크 =>중복이면 빼서 뒤에자리로 옮겨주는작업
=> 0310 update

soyeon/BackJoon_16954_MovingMazeEscape.java, soyeon/Programmers_17680_Cache.java
1. BFS 문제
2. `fall()`과 `fall2()`의 차이
위에 있는 벽부터 아래로 옮겨버리면, 위아래 연달아 벽이 내려올 경우 겹쳐서 처리된다.
---
1. 캐시 hit일 경우 가장 최근의 캐시로 업데이트 안해줘서 tc 11, 15, 18, 19, 20 틀렸었음
=> 2022-03-10 목

soyeon/BackJoon_1956_Exercise.java, soyeon/Programmers_12980_JumpAndTeleport.java
---
플로이드와샬 알고리즘
---
###[프로그래머스_12980_점스와 순간이동]
---
1. Down-Top보단 Top-Down방식이 더 효율적
2. 첨엔 숨바꼭질문제인줄 알고 풀었었는데 효율성 패스못함!
=> 2022-03-14 월

moontek/baekjoon/좋은친구.java, moontek/programmers/방문길이.java
큐 이용문제.. 첫번째값이 몇개의 쌍을 이룰수있는가? 로 접근하면 풀기힘들어지는문제..
이 문제의 포인트는 지금 현재 인원이 기존의 값과 몇개의 쌍을 이룰수있는가라는 거꾸로 접근하는 방식이 필요
이동길이 체크 중복체크
이것만 하면댐 (0,0) -> (1,0) = (1,0) -> (0,0) 이거를 방문처리하고 3차원처리하면끝
=> add 2 quiz 

moontek/baekjoon/두동전.java, moontek/baekjoon/소문난칠공주.java, moontek/programmers/방금그곡.java, moontek/programmers/압축.java
> 두개의 좌표를 클래스로 만들어서 큐에 넣고 bfs 탐색 ,, visited체크를 해줄경우 속도가 엄청빨라짐..
> 25개의 좌표를 dfs 탐색으로 설정하면 오버플로우가난다.. 25개중 7개를 뽑고 좌표로 변환하고 개수 + 연결검사를 해주면되는문제
>  E# 처럼 2글자로 된 문자를 1개로 형변환하여 길이만큼 나열하고 contains로 검사를 해주면 되는 간단한 문제
> 2중 포문으로 구성하여 현재 index   i  (0부터 끝까지) , 중복검사 index j (i부터 끝까지) 로 하여 중복검사후 이전의 값을 더해주고 사전등록해주고 반복
추가적으로 투포인터를 쓰면ㄷ ㅓ깔끔했을것같다.
=>  add : baekjoon 2quiz , pg 2quiz

minjoo/boj4256.java, minjoo/programmers_level2_mostBiggestSquare.java
=> 220413 quiz

moontek/baekjoon/트리.java, moontek/programmers/가장큰정사각형.java
분할정복이라서 골라왓는데 그냥 
입력받은 순위에 대해서 재귀타서 해결하는문제..
가장큰사각형 사각형 기본구조에 대해 자르고자르고 처리하는 dp문제
=> Add :2quiz

minjoo/boj2023.java, minjoo/boj2571.java, minjoo/programmers_level2_yanggungCompetition.java
소수 찾는 알고리즘으로 푸는 문제. 그러나 에라토스테네스의 체가 아닌 다음과 같은 식을 이용하는 게 관건이다.
```java
boolean flag = true;  // true면 소수, flase면 소수 아님
for(int i = 2; i*i<num; i++) {
if(num % i == 0) {
flag = false;
break;
}
}
```
왜냐하면 에라토스테네스의 체를 이용하게 될 경우, N의 최대 크기가 8로 배열의 크기가 arr[10^8]으로 int의 최대인 21억을 넘겨버리는 일이 발생한다. 따라서 그 때마다 소수임을 체크해주는 게 포인트.
---
분할정복?? 문제라길래 긴장했는데 일반 너비 찾이 알고리즘으로 풀어도 해결 됨....
나중에 분할정복으로 다시 풀어볼게요....
---
계속 제출 테케 1, 8번 틀리는데 모르겠어요
열받음
점수차 최소화 하는 문제로 중복 순열로 양궁 화살 꽂이 조합 구하는 건데 엣지 케이스를 못 찾겠어요
=> 220419 quiz

moontek/baekjoon/색종이3.java, moontek/baekjoon/신기한소수.java
누적합 문제!
백트래킹문제 why? ->  메모리지한 4메가
=>  add baek2 quiz

moontek/baekjoon/구슬탈출.java, moontek/baekjoon/시험감독.java
시뮬레이션 2퀴즈
BFS로 4차원 배열 혹은
시뮬레이션으로 풀기..
전자로 나중에 다시풀어보기..
시뮬레이션 풀이는 상하좌우로 10가지의 배치를 만들고 굴려서 MIN값 초기화하면서 진행
주감독 먼저배치하고 서브감독배치후 완
=>  add simul 2quiz

moontek/baekjoon/센서.java, moontek/baekjoon/수묶기.java
=>  add baekjoon 2 quiz

moontek/baekjoon/강의실배정.java, moontek/baekjoon/용액.java
=>  baekjoon quiz upload

moontek/baekjoon/PPAP.java, moontek/baekjoon/합이0인네정수.java
0으로 합만들기
A+B 합 //  C+D합
그리고 자료형 주의하기 
lowerbound upperbound 적용하기
--
PPAP 
P를 입력받았을때 PPAP로 인식하는것도 처리해주기
그리고 A들어올때
앞에 2개가 PP인지 그리고 다음에 오는게 P인지 확인 : PP?P 구조인지확인
그러면 P한개집어넣고 진행하기
그리고 마지막에 저장한공간확인해주면 끝
=>  add : baekjoon 2 quiz

moontek/baekjoon/같은수로만들기.java, moontek/baekjoon/거짓말.java, moontek/baekjoon/경비원.java, moontek/baekjoon/고스택.java, moontek/baekjoon/돌그룹.java, moontek/baekjoon/두배열의합.java, moontek/baekjoon/두수의합.java, moontek/baekjoon/미로탐색.java, moontek/baekjoon/사냥꾼.java, moontek/baekjoon/세훈이의선물가게.java, moontek/baekjoon/영역구하기.java, moontek/baekjoon/오등큰수.java, moontek/baekjoon/오아시스재결합.java, moontek/baekjoon/욕심쟁이판다.java, moontek/baekjoon/움직이는미로탈출.java, moontek/baekjoon/저울.java, moontek/baekjoon/행렬곱셈.java, moontek/baekjoon/호텔.java
여태껏 업데이트 못한 파일들 한방에 업데이트했습니당..
=> update all quiz

moontek/baekjoon/데스노트.java, moontek/baekjoon/쉬운계단수2.java, moontek/baekjoon/일학년.java
=>  add 2quiz dp

minjoo/boj2224.java, minjoo/boj2610.java, minjoo/programmers_level2_differentBitUnderTwoDIgits.java, minjoo/programmers_level2_moreThanSpicy.java
플로이드 와샬 문제.
못 풀었어요....
보자마자 수학 문제였습니다.... 말 그대로 구현하는데 논리연산자를 사용한 문제였어요.
우선순위 큐로 (가장 안 매운 스코빌 지수)+(두 번째로 안 매운 스코빌 지수)*2를 K 이상이 될 때까지 while문을 반복해주면 되는 문제였습니다~~
=> 220726 quiz

minjoo/boj1238.java, minjoo/programmers_level2_gameOfNDecimalNum.java
최악의 시간 복잡도가 O(N^3)인 문제. 플로이드 와샬로 풀림....
다익스트라만 될 줄 알았으나 통과한 것으로 보아 시간이 좀 넉넉하게 주어진 것 같다...! 다음에 다익스트라로 푼 것도 같이 가져올게요 ^_^
---
재귀 문제로 변환해야 하는 숫자가 차수보다 큰 것과 작거나 같을 때를 나눠 분기해주면 되는 문제!! 처음엔 2진수, 8진수 등 정형화된 것만 나오는 줄 알아서 헤맸었다....
=> 220803 quiz

minjoo/boj15683.java, minjoo/boj2573.java
=> 220828 quiz
